### DISCUSSION TITLE
config importing

### DISCUSSION THREAD

**Discussion by jsonmaf1a** [noti-rs/noti#33] [Ideas]
**Description:** source other files to the main configuration
**Usage:**
```toml
import = ["apps/tg.toml", "display.toml"]
# # # # # # # # # # # # # # # # # # # # #
include = ["general.toml"]
```

**Comment by jsonmaf1a** [comment]
or even maybe something like
```toml
[[import]]
path = "path/to/config.toml"
# # # # # # # # # # # # # # # # # # # #
[[import.path = "path/to/config.toml"]]
```
